### ISSUE TITLE
How can i train the model? (Training.csv)

### ISSUE THREAD

**Issue by shiroyasha9** [dev-Roshan-lab/symptom-prdictor#1]
Hey there! I've just started using flask and a beginner when it comes to AI. I wanted to use your code and implement some more functions in it. I downloaded the code, tried running the app.py, got 404. I tried putting ```rf/constipation/diarrhoea/malaise/coma/blister```, got a 'FileNotFoundError'. I tried using your site, was able to get a proper output, here is what I tried, 'http://symptom-predictor-api.herokuapp.com/rf/constipation/diarrhoea/malaise/coma/blister'. 
I know it sounds very stupid but could you guide me through how could I train the model? I could keep using your site but I wanted to do it on a localhost. Could you please help man?

**Comment by dev-Roshan-lab** [comment]
Hello,

First, make sure the URL is correct
If you're using Locally then use 
`http://127.0.0.1:5000/rf/constipation/diarrhoea/malaise/coma/blister`
`127.0.0.1` is your localhost and `5000` is your port.

Training the AI is Pretty straightforward...
In my code, There are two files Training.csv and Testing.csv we basically fit the Training dataset and Testing dataset, here I used Decision Tree Algorithm and it is done by 
```
   clf3 = tree.DecisionTreeClassifier()
   clf3 = clf3.fit(X,y)
```
and  `X is the symptoms` and 'y is there respective diseases for the symptoms X'


for more clarification, I suggest you watch [This](https://www.youtube.com/watch?v=bwZ3Qiuj3i8)

**Comment by awsum0225** [comment]
I'm not able to find the training.csv and testing.csv files in your repo, have you deleted it? @dev-Roshan-lab

**Comment by dev-Roshan-lab** [comment]
> I'm not able to find the training.csv and testing.csv files in your repo, have you deleted it? @dev-Roshan-lab

I have updated the repo, kindly check it.

**Comment by awsum0225** [comment]
@dev-Roshan-lab Thanks for responding
I have added Trainig.csv in my code but I'm still facing an issue

` File "C:\Users\yash_ghodegaonkar\AppData\Local\Programs\Python\Python310\lib\site-packages\pandas\core\indexes\base.py", line 6176, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['back pain', 'abdominal pain', 'mild fever', 'yellow urine', 'yellowing of eyes', 'acute liver failure', 'fluid overload', 'swelling of stomach', 'swelled lymph nodes', 'blurred and distorted vision', 'throat irritation', 'redness of eyes', 'sinus pressure', 'runny nose', 'chest pain', 'weakness in limbs', 'fast heart rate', 'pain during bowel movements', 'pain in anal region', 'bloody stool', 'irritation in anus', 'neck pain', 'swollen legs', 'swollen blood vessels', 'puffy face and eyes', 'enlarged thyroid', 'brittle nails', 'swollen extremeties', 'excessive hunger', 'extra marital contacts', 'drying and tingling lips', 'slurred speech', 'knee pain', 'hip joint pain', 'muscle weakness', 'stiff neck', 'swelling joints', 'movement stiffness', 'spinning movements', 'loss of balance', 'weakness of one body side', 'loss of smell', 'bladder discomfort', 'foul smell of urine', 'continuous feel of urine', 'passage of gases', 'internal itching', 'toxic look (typhos)', 'muscle pain', 'altered sensorium', 'red spots over body', 'belly pain', 'abnormal menstruation', 'dischromic  patches', 'watering from eyes', 'increased appetite', 'family history', 'mucoid sputum', 'rusty sputum', 'lack of concentration', 'visual disturbances', 'receiving blood transfusion', 'receiving unsterile injections', 'stomach bleeding', 'distention of abdomen', 'history of alcohol consumption', 'blood in sputum', 'prominent veins on calf', 'painful walking', 'pus filled pimples', 'skin peeling', 'silver like dusting', 'small dents in nails', 'inflammatory nails', 'red sore around nose', 'yellow crust ooze'] not in index"
`

Can you please help
Also you have not added Testing.csv file in repo
